spring:

  application:
    name: social-platform

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/realtime_social}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-to-a-long-random-production-secret}
    access-token-expiration: ${JWT_ACCESS_EXPIRATION:900000}
    refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.social.platform: INFO
    org.springframework.security: INFO